### ISSUE TITLE
Remove prefix

### ISSUE THREAD

**Issue by ThorHen** [oNaiPs/secrets-to-env-action#294]
Hi,

Not entirely sure whether this is already supported or not.

Is it in some way possible to remove a specified prefix from the secret names, before adding them as environment variables?

Really neat action!

# Example

## GitHub Secrets

MY_PREFIXED_SECRET_1 = ABC
MY_PREFIXED_SECRET_2 = DEF

## YML

```YAML
steps:
- uses: actions/checkout@v3
- uses: oNaiPs/secrets-to-env-action@v1
  with:
    secrets: ${{ toJSON(secrets) }}
    include: my_prefixed_* # Should include both MY_PREFIXED_SECRET_1 and MY_PREFIXED_SECRET_2 
    remove_prefix: my_prefixed_

- run: echo "Value of MY_SECRET: $SECRET_1"
```
